-- 코드를 입력하세요
SELECT 
    REST_INFO.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    REST_INFO.FAVORITES,
    ADDRESS,
    ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) as SCORE
    FROM REST_REVIEW
    JOIN REST_INFO ON REST_REVIEW.REST_ID = REST_INFO.REST_ID
    GROUP BY REST_REVIEW.REST_ID
    HAVING REST_INFO.ADDRESS LIKE '서울%'
    ORDER BY SCORE DESC, FAVORITES DESC;

# SELECT * FROM REST_INFO;
# SELECT * FROM REST_REVIEW;
# SELECT * FROM REST_REVIEW WHERE REST_ID = 19;